spring.application.name=shift-service
server.port=8081
spring.output.ansi.enabled=always

# C?u hình k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shift_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình Hibernate (T? ??ng t?o b?ng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect