
spring.application.name=supplier-service
spring.output.ansi.enabled=always
#Cau hinh ket noi postgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6oocnlm5p6s73de95sg-a:5432/supplier_db_gnap
spring.datasource.username=supplier_db_gnap_user
spring.datasource.password=gC666ttp4WviPvmfFxLEm2nglWxbShXj



#Cau hinh hibernate
spring.jpa.hibernate.ddl-auto=update

#Dang ky voi Eureka Server
eureka.client.service-url.defaultZone=https://microservice-6dyb.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true


